apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: java-app-git
  namespace: java-bc
spec:
  failedBuildsHistoryLimit: 1
  output:
    to:
      kind: ImageStreamTag
      name: java-app:latest
  runPolicy: Serial
  source:
    git:
      ref: main
      uri: https://github.com/BabbarPB08/buildconfig-javatest.git
    sourceSecret:
      name: github-https
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: MAVEN_ARGS
        value: -DskipTests
      from:
        kind: ImageStreamTag
        name: jboss-webserver57-openjdk11-tomcat9-openshift-ubi8:latest
        namespace: openshift
      incremental: false
    type: Source
  successfulBuildsHistoryLimit: 2
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
  - generic:
      secretReference:
        name: github-webhook
    type: Generic
